name: Lint & Test on Push

on: [push]

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Pythonのバージョンを指定
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Run lint
      run: make lint
    - name: Run test
      run: make test
